language: python

python:
  - 3.6
  - 3.7


install:
  - pip install httpretty --quiet
  - pip install .


before_script: rm --recursive --force --verbose *.py[cod]


script:
  - python -m unittest --verbose --locals tests.TestOpenExchangeRates


notifications:
  email:
    recipients: juancarlospaco@gmail.com
    on_success: change
    on_failure: always


cache:
  apt: true
  pip: true


matrix:
  fast_finish: true
  allow_failures:
    - python: 3.7
